function Write-JsonFile {
  param($Path, $Object, [int]$Depth = 20)
  $dir = Split-Path $Path -Parent
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $Object | ConvertTo-Json -Depth $Depth | Set-Content -Path $Path -Encoding UTF8
}

function Write-TextFile {
  param([string]$Path, [string[]]$Lines)
  $dir = Split-Path $Path -Parent
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $Lines | Set-Content -Path $Path -Encoding UTF8
}

function Invoke-AdmittedActionExecutionEngine {
  param(
    [string]$RepoRoot,
    [string]$RunId,
    $Admission,
    [string]$OutputRoot
  )

  Push-Location $RepoRoot

  try {
    if (-not (Test-Path $OutputRoot)) { New-Item -ItemType Directory -Force -Path $OutputRoot | Out-Null }

    $admittedActionPath = "$($Admission.admitted_action_path)"
    if ([string]::IsNullOrWhiteSpace($admittedActionPath)) { throw "Admitted action path is empty." }
    if (-not (Test-Path $admittedActionPath)) { throw "Admitted action missing: $admittedActionPath" }

    $AdmittedAction = Get-Content $admittedActionPath -Raw | ConvertFrom-Json

    $PackId = "PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1"
    $TaskId = "TASK_PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1_001"
    $PackDir = "packs/$PackId"
    $TaskPath = "tasks/$TaskId.json"
    $PackPath = "$PackDir/PACK.json"
    $ApplyPath = "$PackDir/APPLY.ps1"
    $ValidatePath = "$PackDir/VALIDATE.ps1"

    $status = "BLOCKED"
    $reason = ""
    $nextStep = "PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1"

    if (
      $Admission.status -eq "PASS" -and
      $AdmittedAction.status -eq "PASS" -and
      $AdmittedAction.target_capability -eq "ADMITTED_ACTION_EXECUTION_ENGINE" -and
      $AdmittedAction.executed -eq $false
    ) {
      $status = "PASS"
      $reason = "Admitted action is valid. Execution engine created an executable self-build pack/task and queued it as the next Builder-owned move."
    } else {
      $status = "BLOCKED"
      $reason = "Admitted action does not satisfy execution criteria."
      $nextStep = "PHASE115_REVIEW_ADMITTED_ACTION_EXECUTION_BLOCKER_V1"
    }

    if ($status -eq "PASS") {
      New-Item -ItemType Directory -Force -Path $PackDir | Out-Null

      $Pack = [ordered]@{
        pack_id = $PackId
        task_id = $TaskId
        phase = $PackId
        mode = "SELF_BUILD"
        status = "READY"
        shell = "PowerShell"
        entry_script = $ApplyPath
        validate_script = $ValidatePath
        created_by = "ADMITTED_ACTION_EXECUTION_ENGINE_V1"
        source_admitted_action_id = $AdmittedAction.admitted_action_id
        source_admitted_action_path = $admittedActionPath
        autonomous_eligible = $true
        autonomous_priority = 100
        purpose = "Execute the Builder-queued admitted action generated by PHASE114"
        next_allowed_step = "PHASE116_BUILDER_AUTONOMOUS_CHAIN_SMOKE_V1"
      }

      $Task = [ordered]@{
        task_id = $TaskId
        status = "READY"
        mode = "SELF_BUILD"
        phase = $PackId
        active_line = "AGENT_BUILDER / SELF_BUILD"
        created_by = "ADMITTED_ACTION_EXECUTION_ENGINE_V1"
        source_admitted_action_id = $AdmittedAction.admitted_action_id
        source_admitted_action_path = $admittedActionPath
        purpose = "Execute generated admitted-action move and return queue to NONE"
        autonomous_eligible = $true
        codex_used = $false
        next_allowed_step = "PHASE116_BUILDER_AUTONOMOUS_CHAIN_SMOKE_V1"
      }

      Write-JsonFile $PackPath $Pack 12
      Write-JsonFile $TaskPath $Task 12

      $ApplyLines = @(
        "param(",
        "  [string]`$RepoRoot = (Get-Location).Path,",
        "  [string]`$RunId = `"PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1`",",
        "  [switch]`$InvokedByOrchestrator",
        ")",
        "`$ErrorActionPreference = `"Continue`"",
        "`$Ok = `$true",
        "function Mark-Fail { param([string]`$Message) Write-Output `"FAIL=`$Message`"; `$script:Ok = `$false }",
        "function Write-JsonFile { param(`$Path, `$Object, [int]`$Depth = 20) `$dir = Split-Path `$Path -Parent; if (`$dir -and -not (Test-Path `$dir)) { New-Item -ItemType Directory -Force -Path `$dir | Out-Null }; `$Object | ConvertTo-Json -Depth `$Depth | Set-Content -Path `$Path -Encoding UTF8 }",
        "`$PackId = `"PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1`"",
        "`$TaskId = `"TASK_PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1_001`"",
        "`$NextAllowed = `"PHASE116_BUILDER_AUTONOMOUS_CHAIN_SMOKE_V1`"",
        "`$ResultPath = `"self_build_batch/autonomy_trials/`$PackId/`${PackId}_RESULT.json`"",
        "`$ReportPath = `"reports/self_development/`${PackId}_REPORT.json`"",
        "`$ProofPath = `"proofs/self_development/`$PackId.json`"",
        "Push-Location `$RepoRoot",
        "Write-Output `"PHASE115_GENERATED_MOVE_APPLY_START`"",
        "Write-Output `"RUN_ID=`$RunId`"",
        "try {",
        "  `$Queue = Get-Content `"TASK_QUEUE.json`" -Raw | ConvertFrom-Json",
        "  Write-Output `"ACTIVE_TASK_ID_AT_APPLY=`$(`$Queue.active_task_id)`"",
        "  if (`$Queue.active_task_id -ne `$TaskId) { Mark-Fail `"ACTIVE_TASK_ID_NOT_GENERATED_TASK=`$(`$Queue.active_task_id)`" }",
        "  `$tasks = @(`$Queue.tasks)",
        "  `$task = @(`$tasks | Where-Object { `$_.task_id -eq `$TaskId })",
        "  if (`$task.Count -eq 0) { Mark-Fail `"GENERATED_TASK_NOT_FOUND=`$TaskId`" } else { `$task[0].status = `"COMPLETED`" }",
        "  `$Queue.tasks = @(`$tasks)",
        "  `$Queue.active_task_id = `"NONE`"",
        "  Write-JsonFile `"TASK_QUEUE.json`" `$Queue 24",
        "} catch { Mark-Fail `"GENERATED_MOVE_APPLY_ERROR=`$(`$_.Exception.Message)`" }",
        "`$status = if (`$Ok -eq `$true) { `"PASS`" } else { `"FAIL`" }",
        "`$Result = [ordered]@{ status = `$status; phase = `$PackId; task_id = `$TaskId; run_id = `$RunId; runtime_executed = `$true; builder_executed = `$true; generated_by_phase114 = `$true; queue_returned_to_none = `$true; codex_used = `$false; main_touched = `$false; next_allowed_step = `$NextAllowed }",
        "`$Report = [ordered]@{ status = `$status; report_id = `"`${PackId}_REPORT`"; phase = `$PackId; summary = `"Generated admitted-action self-build move executed and returned queue to NONE.`"; next_allowed_step = `$NextAllowed }",
        "`$Proof = [ordered]@{ status = `$status; proof_id = `$PackId; phase = `$PackId; runtime_mode = `"SELF_BUILD_GENERATED_ADMITTED_ACTION_MOVE`"; generated_by_phase114 = `$true; queue_returned_to_none = `$true; codex_used = `$false; main_touched = `$false; result_path = `$ResultPath; report_path = `$ReportPath; next_allowed_step = `$NextAllowed }",
        "Write-JsonFile `$ResultPath `$Result 16",
        "Write-JsonFile `$ReportPath `$Report 16",
        "Write-JsonFile `$ProofPath `$Proof 16",
        "if (`$Ok -eq `$true) { Write-Output `"PHASE115_GENERATED_MOVE_APPLY_RESULT=PASS`"; Write-Output `"TASK_QUEUE_RETURNED_TO_NONE`" } else { Write-Output `"PHASE115_GENERATED_MOVE_APPLY_RESULT=FAIL`" }",
        "Pop-Location",
        "if (`$Ok -ne `$true) { throw `"PHASE115 generated move apply failed.`" }"
      )

      $ValidateLines = @(
        "param(",
        "  [string]`$RepoRoot = (Get-Location).Path,",
        "  [string]`$RunId = `"PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1`",",
        "  [switch]`$InvokedByOrchestrator",
        ")",
        "`$ErrorActionPreference = `"Continue`"",
        "`$Ok = `$true",
        "function Mark-Fail { param([string]`$Message) Write-Output `"FAIL=`$Message`"; `$script:Ok = `$false }",
        "`$PackId = `"PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1`"",
        "`$TaskId = `"TASK_PHASE115_EXECUTE_BUILDER_QUEUED_ADMITTED_ACTION_V1_001`"",
        "`$NextAllowed = `"PHASE116_BUILDER_AUTONOMOUS_CHAIN_SMOKE_V1`"",
        "`$ResultPath = `"self_build_batch/autonomy_trials/`$PackId/`${PackId}_RESULT.json`"",
        "`$ReportPath = `"reports/self_development/`${PackId}_REPORT.json`"",
        "`$ProofPath = `"proofs/self_development/`$PackId.json`"",
        "Push-Location `$RepoRoot",
        "Write-Output `"PHASE115_GENERATED_MOVE_VALIDATE_START`"",
        "foreach (`$p in @(`"TASK_QUEUE.json`", `"packs/registry.json`", `"packs/`$PackId/PACK.json`", `"tasks/`$TaskId.json`")) { if (-not (Test-Path `$p)) { Mark-Fail `"MISSING=`$p`" } else { try { Get-Content `$p -Raw | ConvertFrom-Json | Out-Null; Write-Output `"JSON_PARSE_PASS=`$p`" } catch { Mark-Fail `"JSON_PARSE_FAIL=`$p :: `$(`$_.Exception.Message)`" } } }",
        "try { `$Queue = Get-Content `"TASK_QUEUE.json`" -Raw | ConvertFrom-Json; Write-Output `"ACTIVE_TASK_ID=`$(`$Queue.active_task_id)`" } catch { Mark-Fail `"QUEUE_PARSE_FAIL=`$(`$_.Exception.Message)`" }",
        "if (Test-Path `$ProofPath) { foreach (`$p in @(`$ResultPath, `$ReportPath, `$ProofPath)) { try { `$obj = Get-Content `$p -Raw | ConvertFrom-Json; Write-Output `"OUTPUT_JSON_PARSE_PASS=`$p`"; Write-Output `"OUTPUT_STATUS=`$(`$obj.status)`"; Write-Output `"OUTPUT_NEXT_ALLOWED_STEP=`$(`$obj.next_allowed_step)`"; if (`$obj.status -ne `"PASS`") { Mark-Fail `"OUTPUT_NOT_PASS=`$p`" }; if (`$obj.next_allowed_step -ne `$NextAllowed) { Mark-Fail `"OUTPUT_NEXT_STEP_UNEXPECTED=`$(`$obj.next_allowed_step)`" } } catch { Mark-Fail `"OUTPUT_JSON_PARSE_FAIL=`$p :: `$(`$_.Exception.Message)`" } }; if (`$Queue.active_task_id -ne `"NONE`") { Mark-Fail `"QUEUE_NOT_NONE_AFTER_EXECUTION=`$(`$Queue.active_task_id)`" } } else { if (`$Queue.active_task_id -ne `$TaskId) { Mark-Fail `"QUEUE_NOT_READY_FOR_GENERATED_TASK=`$(`$Queue.active_task_id)`" } }",
        "if (`$Ok -eq `$true) { Write-Output `"PHASE115_GENERATED_MOVE_VALIDATE_RESULT=PASS`" } else { Write-Output `"PHASE115_GENERATED_MOVE_VALIDATE_RESULT=FAIL`" }",
        "Pop-Location",
        "if (`$Ok -ne `$true) { throw `"PHASE115 generated move validate failed.`" }"
      )

      Write-TextFile $ApplyPath $ApplyLines
      Write-TextFile $ValidatePath $ValidateLines

      $Queue = Get-Content "TASK_QUEUE.json" -Raw | ConvertFrom-Json
      $Registry = Get-Content "packs/registry.json" -Raw | ConvertFrom-Json
      $PackObj = Get-Content $PackPath -Raw | ConvertFrom-Json
      $TaskObj = Get-Content $TaskPath -Raw | ConvertFrom-Json

      $tasks = @($Queue.tasks)
      $tasks = @($tasks | Where-Object { $_.task_id -ne $TaskId })
      $tasks += $TaskObj
      $Queue.tasks = @($tasks)
      $Queue.active_task_id = $TaskId

      $packs = @($Registry.packs)
      $packs = @($packs | Where-Object { $_.pack_id -ne $PackId })
      $packs = @($PackObj) + $packs
      $Registry.packs = @($packs)

      Write-JsonFile "TASK_QUEUE.json" $Queue 24
      Write-JsonFile "packs/registry.json" $Registry 24
    }

    $ExecutableMove = [ordered]@{
      status = $status
      engine_name = "ADMITTED_ACTION_EXECUTION_ENGINE_V1"
      run_id = $RunId
      source_admitted_action_path = $admittedActionPath
      generated_pack_id = $PackId
      generated_task_id = $TaskId
      generated_pack_path = $PackPath
      generated_task_path = $TaskPath
      queue_active_task_id_written = ($status -eq "PASS")
      active_task_id = if ($status -eq "PASS") { $TaskId } else { "NONE" }
      executed_generated_move = $false
      proposed_next_step = $nextStep
      reason = $reason
      autonomy_claimed = $false
      codex_used = $false
    }

    $ExecutableMovePath = Join-Path $OutputRoot "EXECUTABLE_SELF_BUILD_MOVE.json"
    $OutputPath = Join-Path $OutputRoot "ADMITTED_ACTION_EXECUTION_ENGINE_OUTPUT.json"

    Write-JsonFile $ExecutableMovePath $ExecutableMove 20
    Write-JsonFile $OutputPath $ExecutableMove 20

    $ExecutableMove["output_path"] = $OutputPath
    $ExecutableMove["executable_move_path"] = $ExecutableMovePath

    return [pscustomobject]$ExecutableMove
  } finally {
    Pop-Location
  }
}
